name: Donation EXcraft
version: 1.0
main: com.example.DonationEXcraft
api-version: 1.20
commands:
  linktoken:
    description: Link your Minecraft account with DonationAlerts token
    usage: /linktoken <token>
permissions:
  donationexcraft.linktoken:
    description: Allows linking DonationAlerts token
    default: true
